GET http://localhost:3000/users?username= sysafarila

###

GET http://localhost:3000/users/449fd667-d361-4661-9688-5b7ef3687669

###

POST http://localhost:3000/register
Content-Type: application/json
Accept: application/json

{
  "username": "sysafarila",
  "full_name": "Syahrul Safarila",
  "password": "password"
}
    
###

POST http://localhost:3000/login
Content-Type: application/json
Accept: application/json

{
  "username": "sysafarila",
  "password": "password"
}

###

POST http://localhost:3000/transactions
Content-Type: application/json
Accept: application/json
x-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODkxOTc1NzMsImlhdCI6MTc4ODU5Mjc3MywiaXNzIjoic3lzYWZhcmlsYSIsInN1YiI6IlN5YWhydWwgU2FmYXJpbGEiLCJ1c2VyX2lkIjoiMzJhODhiYmEtMzAyYS00YWY5LTkwNzAtZmEyMWU2NDg2NTNjIn0.1rxIYfC2n6tkC-DDLxYeuc6K46p39-zfmrMv_oz7Z68

{
  "amount": 20000,
  "description": "makan daging",
  "is_income": false,
  "date": "2026-09-05T14:30:00Z"
}

###

GET http://localhost:3000/transactions
Content-Type: application/json
Accept: application/json
x-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODkxOTc1NzMsImlhdCI6MTc4ODU5Mjc3MywiaXNzIjoic3lzYWZhcmlsYSIsInN1YiI6IlN5YWhydWwgU2FmYXJpbGEiLCJ1c2VyX2lkIjoiMzJhODhiYmEtMzAyYS00YWY5LTkwNzAtZmEyMWU2NDg2NTNjIn0.1rxIYfC2n6tkC-DDLxYeuc6K46p39-zfmrMv_oz7Z68

###

PATCH http://localhost:3000/transactions/3c498d5a-06c1-4d22-926d-f39285596e29
Content-Type: application/json
Accept: application/json
x-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODkxOTc1NzMsImlhdCI6MTc4ODU5Mjc3MywiaXNzIjoic3lzYWZhcmlsYSIsInN1YiI6IlN5YWhydWwgU2FmYXJpbGEiLCJ1c2VyX2lkIjoiMzJhODhiYmEtMzAyYS00YWY5LTkwNzAtZmEyMWU2NDg2NTNjIn0.1rxIYfC2n6tkC-DDLxYeuc6K46p39-zfmrMv_oz7Z68

{
  "amount": 20000,
  "description": "makan daging ayam",
  "is_income": true,
  "date": "2026-09-05T14:30:00Z"
}

###

DELETE http://localhost:3000/transactions/65762b90-a37f-447a-8409-cda04249d26fzzzzz
Content-Type: application/json
Accept: application/json
x-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODkxOTc1NzMsImlhdCI6MTc4ODU5Mjc3MywiaXNzIjoic3lzYWZhcmlsYSIsInN1YiI6IlN5YWhydWwgU2FmYXJpbGEiLCJ1c2VyX2lkIjoiMzJhODhiYmEtMzAyYS00YWY5LTkwNzAtZmEyMWU2NDg2NTNjIn0.1rxIYfC2n6tkC-DDLxYeuc6K46p39-zfmrMv_oz7Z68