POST http://localhost:3000/register
Content-Type: application/json
Accept: application/json

{
  "username": "sysafarila",
  "full_name": "Syahrul Safarila",
  "password": "password"
}
    
###

POST http://localhost:3000/login
Content-Type: application/json
Accept: application/json

{
  "username": "sysafarila",
  "password": "password"
}

###

POST http://localhost:3000/transactions
Content-Type: application/json
Accept: application/json
x-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODk4MjM3ODYsImlhdCI6MTc4OTIxODk4NiwiaXNzIjoic3lzYWZhcmlsYSIsInN1YiI6IlN5YWhydWwgU2FmYXJpbGEiLCJ1c2VyX2lkIjoiMzJhODhiYmEtMzAyYS00YWY5LTkwNzAtZmEyMWU2NDg2NTNjIn0.vT-6kIWxFhQMGZ2lHJL9M41n26u3J6d4lL8aSzmb9K0

{
  "amount": 20000,
  "description": "makan daging",
  "is_income": false,
  "date": "2026-09-05T14:30:00Z",
  "category_id": "894384dc-ed8a-412e-a672-b57c3f2327df"
}

###

GET http://localhost:3000/transactions/1e2d3598-93fe-4b54-89d8-b9eb9bd271da
Content-Type: application/json
Accept: application/json
x-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODk4MjM3ODYsImlhdCI6MTc4OTIxODk4NiwiaXNzIjoic3lzYWZhcmlsYSIsInN1YiI6IlN5YWhydWwgU2FmYXJpbGEiLCJ1c2VyX2lkIjoiMzJhODhiYmEtMzAyYS00YWY5LTkwNzAtZmEyMWU2NDg2NTNjIn0.vT-6kIWxFhQMGZ2lHJL9M41n26u3J6d4lL8aSzmb9K0

###

PATCH http://localhost:3000/transactions/3c498d5a-06c1-4d22-926d-f39285596e29
Content-Type: application/json
Accept: application/json
x-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODkxOTc1NzMsImlhdCI6MTc4ODU5Mjc3MywiaXNzIjoic3lzYWZhcmlsYSIsInN1YiI6IlN5YWhydWwgU2FmYXJpbGEiLCJ1c2VyX2lkIjoiMzJhODhiYmEtMzAyYS00YWY5LTkwNzAtZmEyMWU2NDg2NTNjIn0.1rxIYfC2n6tkC-DDLxYeuc6K46p39-zfmrMv_oz7Z68

{
  "amount": 20000,
  "description": "makan daging ayam",
  "is_income": true,
  "date": "2026-09-05T14:30:00Z"
}

###

DELETE http://localhost:3000/transactions/65762b90-a37f-447a-8409-cda04249d26fzzzzz
Content-Type: application/json
Accept: application/json
x-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODkxOTc1NzMsImlhdCI6MTc4ODU5Mjc3MywiaXNzIjoic3lzYWZhcmlsYSIsInN1YiI6IlN5YWhydWwgU2FmYXJpbGEiLCJ1c2VyX2lkIjoiMzJhODhiYmEtMzAyYS00YWY5LTkwNzAtZmEyMWU2NDg2NTNjIn0.1rxIYfC2n6tkC-DDLxYeuc6K46p39-zfmrMv_oz7Z68

###
GET http://localhost:3000/categories
Content-Type: application/json
Accept: application/json
x-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODk4MjM3ODYsImlhdCI6MTc4OTIxODk4NiwiaXNzIjoic3lzYWZhcmlsYSIsInN1YiI6IlN5YWhydWwgU2FmYXJpbGEiLCJ1c2VyX2lkIjoiMzJhODhiYmEtMzAyYS00YWY5LTkwNzAtZmEyMWU2NDg2NTNjIn0.vT-6kIWxFhQMGZ2lHJL9M41n26u3J6d4lL8aSzmb9K0

###
POST http://localhost:3000/categories
Content-Type: application/json
Accept: application/json
x-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODk4MjM3ODYsImlhdCI6MTc4OTIxODk4NiwiaXNzIjoic3lzYWZhcmlsYSIsInN1YiI6IlN5YWhydWwgU2FmYXJpbGEiLCJ1c2VyX2lkIjoiMzJhODhiYmEtMzAyYS00YWY5LTkwNzAtZmEyMWU2NDg2NTNjIn0.vT-6kIWxFhQMGZ2lHJL9M41n26u3J6d4lL8aSzmb9K0

{
  "name": "xyz"
}

###
PATCH http://localhost:3000/categories/d39d1d02-099e-4b43-b249-894ffb096e43
Content-Type: application/json
Accept: application/json
x-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODk4MjM3ODYsImlhdCI6MTc4OTIxODk4NiwiaXNzIjoic3lzYWZhcmlsYSIsInN1YiI6IlN5YWhydWwgU2FmYXJpbGEiLCJ1c2VyX2lkIjoiMzJhODhiYmEtMzAyYS00YWY5LTkwNzAtZmEyMWU2NDg2NTNjIn0.vT-6kIWxFhQMGZ2lHJL9M41n26u3J6d4lL8aSzmb9K0

{
  "name": "xyz2"
}

###
DELETE http://localhost:3000/categories/d39d1d02-099e-4b43-b249-894ffb096e43
Content-Type: application/json
Accept: application/json
x-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODk4MjM3ODYsImlhdCI6MTc4OTIxODk4NiwiaXNzIjoic3lzYWZhcmlsYSIsInN1YiI6IlN5YWhydWwgU2FmYXJpbGEiLCJ1c2VyX2lkIjoiMzJhODhiYmEtMzAyYS00YWY5LTkwNzAtZmEyMWU2NDg2NTNjIn0.vT-6kIWxFhQMGZ2lHJL9M41n26u3J6d4lL8aSzmb9K0